version: '3'

services:
  spark-master:
    image: bitnami/spark:latest
    command: bin/spark-class org.apache.spark.deploy.master.Master
    ports:
      - "8080:8080" # Spark Web UI
      - "7077:7077" # Spark Master Port
    volumes:
      - ./mongo-spark-connector-10.0.4-all.jar:/opt/spark/jars/mongo-spark-connector.jar

  spark-worker:
    image: bitnami/spark:latest
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    depends_on:
      - spark-master
    environment:
      SPARK_MODE: worker
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 1g
      SPARK_MASTER_URL: spark://spark-master:7077
    volumes:
      - ./mongo-spark-connector-10.0.4-all.jar:/opt/spark/jars/mongo-spark-connector.jar


  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - spark-master
      - mongodb
    volumes:
      - ./src:/app/src
      - ./data:/app/data

volumes:
  mongo_data:
