version: '3'

services:
  spark-master:
    image: bitnami/spark:latest
    command: bin/spark-class org.apache.spark.deploy.master.Master
    ports:
      - "9090:8080" # Spark Web UI
      - "7077:7077" # Spark Master Port
    networks:
      - spark
    volumes:
      - ./mongo-spark-connector-10.0.4-all.jar:/opt/spark/jars/mongo-spark-connector.jar

  spark-worker:
    image: bitnami/spark:latest
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    depends_on:
      - spark-master
    environment:
      SPARK_MODE: worker
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 1g
      SPARK_MASTER_URL: spark://spark-master:7077
    networks:
      - spark
    volumes:
      - ./mongo-spark-connector-10.0.4-all.jar:/opt/spark/jars/mongo-spark-connector.jar

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000" # FastAPI Port
    depends_on:
      - spark-master
    networks:
      - spark
    environment:
      - MONGO_URI=mongodb://samirziani:samir5636123@cluster0-shard-00-00.mongodb.net:27017,cluster0-shard-00-01.mongodb.net:27017,cluster0-shard-00-02.mongodb.net:27017/?ssl=true&replicaSet=atlas-xxx-shard-0&authSource=admin&retryWrites=true&w=majority
      - DATABASE_NAME=sample_mflix
      - COLLECTION_NAME=articles
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_MONGO_URI=mongodb://samirziani:samir5636123@cluster0-shard-00-00.mongodb.net:27017,cluster0-shard-00-01.mongodb.net:27017,cluster0-shard-00-02.mongodb.net:27017/sample_mflix.articles?ssl=true&replicaSet=atlas-xxx-shard-0&authSource=admin&retryWrites=true&w=majority

    volumes:
      - ./src:/app/src
networks:
  spark:
